version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/:/mosquitto/config
    ports:
      - 1883:1883

  mosquitto-bridge:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto-bridge/config/:/mosquitto/config
