version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/:/mosquitto/config
    ports:
      - 31883:11883

  mosquitto-bridge:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto-bridge/config/:/mosquitto/config
    depends_on:
      - mosquitto

  nuttynios-frontend:
    build:
      context: ./NuttyNios-Frontend
      dockerfile: Dockerfile
    ports:
      - 49160:10000
    depends_on:
      - mosquitto-bridge

  nuttynios-endpoints:
    build:
      context: ./NuttyNios-Endpoints
      dockerfile: Dockerfile
    ports:
      - 18000:18000
    depends_on:
      - mosquitto-bridge
