version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/:/mosquitto/config
    ports:
      - 31883:11883

  mosquitto-bridge:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto-bridge/config/:/mosquitto/config
    depends_on:
      - mosquitto

  nuttynios-frontend-client:
    build:
      context: ./NuttyNios-Frontend
      dockerfile: Dockerfile.client
    ports:
      - 49160:10000
    depends_on:
      - mosquitto-bridge
 
  nuttynios-frontend-server:
    build:
      context: ./NuttyNios-Frontend
      dockerfile: Dockerfile.server
    ports:
      - 2567:2567
    depends_on:
      - mosquitto-bridge
