version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/:/mosquitto/config
    ports:
      - 1883:11883

  mosquitto-bridge:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto-bridge/config/:/mosquitto/config
    depends_on:
      - mosquitto

  nuttynios-frontend:
    image: nuttynios-frontend
    build:
      context: ./NuttyNios-Frontend
      dockerfile: Dockerfile
    depends_on:
      - mosquitto-bridge
